version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/packages/omniwrap"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "uv"
    directory: "/packages/omniray"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
    commit-message:
      prefix: "ci"
