name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: "Breaking"
    labels:
      - "major"
  - title: "Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "CI/CD"
    labels:
      - "ci"
  - title: "Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "Maintenance"
    labels:
      - "chore"
  - title: "Other changes"
  - title: "Dependencies"
    labels:
      - "dependencies"
    collapse-after: 5

autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.*\))?:/i'
  - label: "fix"
    title:
      - '/^fix(\(.*\))?:/i'
  - label: "ci"
    title:
      - '/^ci(\(.*\))?:/i'
    files:
      - ".github/**"
  - label: "docs"
    title:
      - '/^docs(\(.*\))?:/i'
    files:
      - "docs/**"
      - "README.md"
  - label: "chore"
    title:
      - '/^chore(\(.*\))?:/i'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feat"
      - "feature"
  patch:
    labels:
      - "fix"
      - "bugfix"
      - "bug"
      - "chore"
      - "ci"
      - "docs"
      - "dependencies"
  default: patch

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

exclude-labels:
  - "skip-changelog"
