name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "ci"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feat"
      - "minor"
      - "feature"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

autolabeler:
  - label: 'feat'
    title:
      - '/^feat(\(.*\))?:/i'
  - label: 'fix'
    title:
      - '/^fix(\(.*\))?:/i'
  - label: 'docs'
    title:
      - '/^docs(\(.*\))?:/i'
  - label: 'chore'
    title:
      - '/^chore(\(.*\))?:/i'
