sonar.organization=omniviser
sonar.projectKey=omniviser_omniray
sonar.projectName=omniray

sonar.sources=packages/omniwrap/omniwrap,packages/omniray/omniray
sonar.tests=packages/omniwrap/tests,packages/omniray/tests

sonar.exclusions=**/tests/**,**/examples/**,**/benchmarks/**,**/__pycache__/**
sonar.cpd.exclusions=**/tests/**

sonar.python.version=3.12,3.13,3.14
sonar.python.coverage.reportPaths=packages/omniwrap/coverage.xml,packages/omniray/coverage.xml
