name: SBOM

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          artifact-name: sbom-omniwrap.spdx.json
          output-file: sbom-omniwrap.spdx.json
          path: packages/omniwrap/

      - uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          artifact-name: sbom-omniray.spdx.json
          output-file: sbom-omniray.spdx.json
          path: packages/omniray/
