name: SBOM

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
        with:
          artifact-name: sbom-omniwrap.spdx.json
          output-file: sbom-omniwrap.spdx.json
          path: packages/omniwrap/

      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
        with:
          artifact-name: sbom-omniray.spdx.json
          output-file: sbom-omniray.spdx.json
          path: packages/omniray/
